'use client'

import { useState, useEffect, useMemo } from 'react'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Sparkles, RefreshCw, Loader2 } from 'lucide-react'
import {
  geographicBreakdown, sectorBreakdown, currencyBreakdown, concentrationMetrics,
} from '@/lib/analytics'
import type { TickerAnalytics } from '@/app/api/analytics/route'
import type { Currency, EnrichedHolding, PortfolioStats } from '@/types'

interface Props {
  enriched: EnrichedHolding[]
  stats: PortfolioStats | null
  baseCurrency: Currency
}

const CACHE_KEY = 'portfolio-summary-v1'
const CACHE_TTL_MS = 24 * 60 * 60 * 1000  // 24h

interface CachedSummary {
  summary: string
  generatedAt: number
  fingerprint: string
}

// Cheap fingerprint of the portfolio so we know to regenerate when things change
function fingerprint(enriched: EnrichedHolding[], stats: PortfolioStats | null): string {
  const parts: string[] = []
  parts.push(`${stats?.totalValue.toFixed(0) ?? 0}`)
  for (const h of [...enriched].sort((a, b) => a.ticker.localeCompare(b.ticker))) {
    parts.push(`${h.ticker}:${h.allocationPct.toFixed(1)}`)
  }
  return parts.join('|')
}

export function PortfolioSummaryWidget({ enriched, stats, baseCurrency }: Props) {
  const [analytics, setAnalytics] = useState<Record<string, TickerAnalytics>>({})
  const [summary, setSummary] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const fp = useMemo(() => fingerprint(enriched, stats), [enriched, stats])

  // Try cache on mount
  useEffect(() => {
    if (typeof window === 'undefined') return
    try {
      const raw = localStorage.getItem(CACHE_KEY)
      if (!raw) return
      const parsed = JSON.parse(raw) as CachedSummary
      const fresh = Date.now() - parsed.generatedAt < CACHE_TTL_MS
      if (fresh && parsed.fingerprint === fp) setSummary(parsed.summary)
    } catch { /* ignore */ }
  }, [fp])

  // Fetch analytics for breakdowns
  useEffect(() => {
    if (enriched.length === 0) return
    fetch('/api/analytics', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ tickers: enriched.map((h) => h.ticker) }),
    })
      .then((r) => r.json())
      .then((data) => setAnalytics(data.analytics ?? {}))
      .catch(() => { /* widget will still try with empty analytics */ })
  }, [enriched.length]) // eslint-disable-line react-hooks/exhaustive-deps

  const generate = async () => {
    if (!stats) return
    setLoading(true)
    setError(null)
    try {
      const top = [...enriched]
        .sort((a, b) => b.currentValueBase - a.currentValueBase)
        .slice(0, 8)
        .map((h) => ({
          ticker: h.ticker,
          name: h.name,
          pct: h.allocationPct,
          gainPct: h.gainLossPct,
        }))
      const geo = geographicBreakdown(enriched, analytics)
      const sec = sectorBreakdown(enriched, analytics)
      const cur = currencyBreakdown(enriched, analytics)
      const conc = concentrationMetrics(enriched)

      const res = await fetch('/api/summary', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          baseCurrency,
          totalValue: stats.totalValue,
          totalCost: stats.totalCost,
          totalGainPct: stats.totalGainLossPct,
          dayChangePct: stats.totalDayChangePct,
          holdingsCount: enriched.length,
          topHoldings: top,
          geographic: geo,
          sectors: sec,
          currencies: cur,
          concentration: conc,
        }),
      })

      const data = await res.json()
      if (!res.ok) {
        setError(data.error ?? 'Failed to generate summary')
        return
      }
      const text = data.summary ?? ''
      setSummary(text)
      // Cache it
      try {
        const cached: CachedSummary = { summary: text, generatedAt: Date.now(), fingerprint: fp }
        localStorage.setItem(CACHE_KEY, JSON.stringify(cached))
      } catch { /* ignore quota */ }
    } catch (err) {
      setError(`Failed to generate summary: ${String(err)}`)
    } finally {
      setLoading(false)
    }
  }

  return (
    <Card>
      <CardHeader>
        <div className="flex items-start justify-between gap-3">
          <div>
            <CardTitle className="text-base flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-primary" /> Plain-English summary
            </CardTitle>
            <CardDescription>One-paragraph narrative of your portfolio. Generated by Claude.</CardDescription>
          </div>
          <Button variant="outline" size="sm" onClick={generate} disabled={loading || enriched.length === 0}>
            {loading
              ? <><Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> Thinking…</>
              : summary
                ? <><RefreshCw className="mr-1.5 h-3.5 w-3.5" /> Regenerate</>
                : <><Sparkles className="mr-1.5 h-3.5 w-3.5" /> Generate</>}
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        {error ? (
          <div className="rounded-md bg-amber-500/10 px-3 py-2 text-xs text-amber-400 space-y-1">
            <div>{error}</div>
            {error.includes('ANTHROPIC_API_KEY') && (
              <div className="text-muted-foreground">
                Add <code className="text-xs">ANTHROPIC_API_KEY</code> to <code className="text-xs">.env.local</code> and restart the dev server.
              </div>
            )}
          </div>
        ) : summary ? (
          <div className="space-y-3">
            {summary.split(/\n\n+/).map((p, i) => (
              <p key={i} className="text-sm leading-relaxed text-foreground/90">{p}</p>
            ))}
          </div>
        ) : (
          <p className="text-sm text-muted-foreground">
            Click <em>Generate</em> for a 2-paragraph narrative based on your current allocation, returns, and concentration metrics.
          </p>
        )}
      </CardContent>
    </Card>
  )
}
