/**
 * Prebuild script — removes the conflicting (dashboard)/page.tsx that was
 * generated by create-next-app scaffolding. Both app/page.tsx and
 * app/(dashboard)/page.tsx resolve to "/" which breaks Vercel's build.
 * Deleting it here is safe: app/page.tsx handles "/" with a redirect to /dashboard.
 */
const fs = require('fs')
const path = require('path')

const conflicting = path.join(__dirname, '../src/app/(dashboard)/page.tsx')

if (fs.existsSync(conflicting)) {
  fs.unlinkSync(conflicting)
  console.log('✓ Removed conflicting src/app/(dashboard)/page.tsx')
} else {
  console.log('✓ No conflicting page.tsx found (already removed)')
}
